name: kalshi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  formz: ^0.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: any
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  go_router: ^13.2.0
  score_repository:
    path: packages/score_repository
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/launcher_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/launcher_icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/launcher_icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/kalshi_logo_black.svg
    - assets/kalshi_logo_round.svg
    - assets/dollar_sign.svg
    - assets/lock.svg
    - assets/healthy_score.svg
    - assets/average_score.svg
    - assets/caution_score.svg

  
